### ISSUE TITLE
add link) which will walk you through creating your first webpage. You can also explore how to [create your first webpage](https://docs.microsoft.com/learn/modules/build-simple-website/?WT.mc_id=academic-0000-cxa) on Microsoft Learn.

### ISSUE THREAD

**Issue by HaHaBlah1** [microsoft/hackwithazure#22]
```
If you are attending a [TechTogether][def] hackathon, you can attend the [HTML and CSS workshop](TODO: add link) which will walk you through creating your first webpage. You can also explore how to [create your first webpage](https://docs.microsoft.com/learn/modules/build-simple-website/?WT.mc_id=academic-0000-cxa) on Microsoft Learn.
```

https://github.com/microsoft/hackwithazure/blob/4fef410ea7088a90c8e568036190888db41aa8ae/localhost.md#L41
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [x] https://github.com/microsoft/hackwithazure/issues/23
```

```[tasklist]
### Tasks
- [x] https://github.com/microsoft/hackwithazure/issues/24
- [ ] https://github.com/microsoft/hackwithazure/issues/23
```

**Comment by HaHaBlah1** [comment]
@fruzinck89
